name: CI/CD Docker

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository }}:latest

            - name: Build and push API
              uses: docker/build-push-action@v6
              with:
                  context: .
                  target: api
                  push: true
                  tags: ghcr.io/${{ github.repository }}:api

    deploy:
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to server
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.HOST }}
                  username: root
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  script: |
                      if [ ! -d "morte-library" ]; then
                        git clone https://github.com/${{ github.repository }}.git morte-library
                      fi
                      cd morte-library
                      git reset --hard HEAD
                      git pull
                      if [ ! -f .env ]; then cp .env.example .env; fi
                      echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
                      sudo docker system prune -a -f || true
                      docker compose pull
                      docker compose up -d
